#!/usr/bin/env bash
# Este script configura la resolución de localhost y facebook.com

# Hacer un backup del archivo /etc/hosts
sudo cp /etc/hosts /etc/hosts.backup

# Cambiar localhost a 127.0.0.2 y facebook.com a 8.8.8.8
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "Resoluciones de IP actualizadas."